FROM: lgirardi/lg-baseimg:edge

LABEL author="k8s.it <l@k8s.it>"
LABEL layer=flask
LABEL area=platform

RUN apt-get update -y && apt-get install -y python3 python3-pip && \
    rm -rf /var/lib/apt/lists/*



